name: qr_scanner
description: A new Flutter project.

publish_to: "none"

version: 2.1.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clay_containers: ^0.3.2
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  
  flutter_native_splash: ^1.2.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.21.0+1
  flutter_web_browser: ^0.15.0
  fluttertoast: ^8.0.3
  hydrated_bloc: ^7.0.0
  image_picker: ^0.7.4
  native_admob_flutter: ^1.5.0
  path_provider: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  screenshot: ^1.0.0-nullsafety.1
  share: ^2.0.1
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  wc_flutter_share: ^0.4.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  recognition_qrcode: ^0.0.7
  validated: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  # flutter_file_dialog: ^2.1.1
  file_saver: ^0.0.10

  
flutter_icons:
  android: false
  ios: true
  image_path: "images/splash.png"

  
flutter_native_splash:  
  color: "#ffffff"
  color_dark: "#000000"
  image: images/splash.png
  android: true
  ios: true
  fullscreen: true



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - locales/
