name: qr_scanner
description: A new Flutter project.

publish_to: "none"

version: 1.2.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clay_containers: ^0.3.2
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  flutter_file_dialog: ^2.0.0
  flutter_svg: ^0.21.0+1
  flutter_web_browser: ^0.14.0
  fluttertoast: ^8.0.3
  hydrated_bloc: ^7.0.0
  image_picker: ^0.7.4
  in_app_review: ^2.0.1
  native_admob_flutter: ^1.2.1
  path_provider: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  screenshot: ^1.0.0-nullsafety.1
  share: ^2.0.1
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  yaml: ^3.1.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  recognition_qrcode: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - locales/
