name: qr_scanner
description: A new Flutter project.

publish_to: "none"

version: 2.4.0+14

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clay_containers: ^0.3.2
  connectivity_plus: ^2.2.2
  cupertino_icons: ^1.0.4
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.3
  flutter_web_browser: ^0.17.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  persistent_bottom_nav_bar: ^4.0.2
  screenshot: ^1.2.3
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  url_launcher: ^6.0.20
  wc_flutter_share: ^0.4.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  recognition_qrcode: ^1.0.1+2
  validated: ^2.0.0
  file_saver: ^0.1.0
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  sliding_switch: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
  google_mobile_ads: ^1.2.0
#  admob_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - locales/

flutter_icons:
  android: false
  ios: true
  image_path: "images/icon.png"
# flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: images/splash.png
  android: false
  ios: true
  fullscreen: true
# flutter pub run flutter_native_splash:create
