name: qr_scanner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clay_containers: ^0.3.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  flutter_bloc: ^7.0.0
  flutter_qr_reader: ^1.0.5
  fluttertoast: ^8.0.3
  image_picker: ^0.7.4
  persistent_bottom_nav_bar: ^4.0.2
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  share: ^2.0.1
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  flutter_web_browser: ^0.14.0
  screenshot: ^1.0.0-nullsafety.1
  flutter_file_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
